// <auto-generated />
using System;
using INFT3050.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace INFT3050.Migrations
{
    [DbContext(typeof(VitaStoreContext))]
    [Migration("20240731094159_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("INFT3050.Models.Image", b =>
                {
                    b.Property<int>("ImageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImageID"));

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ItemID")
                        .HasColumnType("int");

                    b.HasKey("ImageID");

                    b.HasIndex("ItemID");

                    b.ToTable("Images");

                    b.HasData(
                        new
                        {
                            ImageID = 1,
                            ImagePath = "fish_oil.png",
                            ItemID = 1
                        },
                        new
                        {
                            ImageID = 2,
                            ImagePath = "eye_lutein.png",
                            ItemID = 2
                        },
                        new
                        {
                            ImageID = 3,
                            ImagePath = "vitamin_c.png",
                            ItemID = 3
                        },
                        new
                        {
                            ImageID = 4,
                            ImagePath = "product4.jpg",
                            ItemID = 4
                        },
                        new
                        {
                            ImageID = 5,
                            ImagePath = "product5.jpg",
                            ItemID = 5
                        },
                        new
                        {
                            ImageID = 6,
                            ImagePath = "product6.jpg",
                            ItemID = 6
                        },
                        new
                        {
                            ImageID = 7,
                            ImagePath = "product7.jpg",
                            ItemID = 7
                        },
                        new
                        {
                            ImageID = 8,
                            ImagePath = "product8.jpg",
                            ItemID = 8
                        },
                        new
                        {
                            ImageID = 9,
                            ImagePath = "product9.jpg",
                            ItemID = 9
                        },
                        new
                        {
                            ImageID = 10,
                            ImagePath = "product10.jpg",
                            ItemID = 10
                        },
                        new
                        {
                            ImageID = 11,
                            ImagePath = "product11.jpg",
                            ItemID = 11
                        },
                        new
                        {
                            ImageID = 12,
                            ImagePath = "product12.jpg",
                            ItemID = 12
                        },
                        new
                        {
                            ImageID = 13,
                            ImagePath = "product13.jpg",
                            ItemID = 13
                        },
                        new
                        {
                            ImageID = 14,
                            ImagePath = "product14.jpg",
                            ItemID = 14
                        },
                        new
                        {
                            ImageID = 15,
                            ImagePath = "product15.jpg",
                            ItemID = 15
                        },
                        new
                        {
                            ImageID = 16,
                            ImagePath = "product16.jpg",
                            ItemID = 16
                        },
                        new
                        {
                            ImageID = 17,
                            ImagePath = "product17.jpg",
                            ItemID = 17
                        },
                        new
                        {
                            ImageID = 18,
                            ImagePath = "product18.jpg",
                            ItemID = 18
                        },
                        new
                        {
                            ImageID = 19,
                            ImagePath = "product19.jpg",
                            ItemID = 19
                        },
                        new
                        {
                            ImageID = 20,
                            ImagePath = "product20.jpg",
                            ItemID = 20
                        },
                        new
                        {
                            ImageID = 21,
                            ImagePath = "product21.jpg",
                            ItemID = 21
                        },
                        new
                        {
                            ImageID = 22,
                            ImagePath = "product22.jpg",
                            ItemID = 22
                        },
                        new
                        {
                            ImageID = 23,
                            ImagePath = "product23.jpg",
                            ItemID = 23
                        },
                        new
                        {
                            ImageID = 24,
                            ImagePath = "product24.jpg",
                            ItemID = 24
                        },
                        new
                        {
                            ImageID = 25,
                            ImagePath = "product25.jpg",
                            ItemID = 25
                        },
                        new
                        {
                            ImageID = 26,
                            ImagePath = "product26.jpg",
                            ItemID = 26
                        },
                        new
                        {
                            ImageID = 27,
                            ImagePath = "product27.jpg",
                            ItemID = 27
                        },
                        new
                        {
                            ImageID = 28,
                            ImagePath = "product28.jpg",
                            ItemID = 28
                        },
                        new
                        {
                            ImageID = 29,
                            ImagePath = "product29.jpg",
                            ItemID = 29
                        },
                        new
                        {
                            ImageID = 30,
                            ImagePath = "product30.jpg",
                            ItemID = 30
                        },
                        new
                        {
                            ImageID = 31,
                            ImagePath = "product31.jpg",
                            ItemID = 31
                        },
                        new
                        {
                            ImageID = 32,
                            ImagePath = "product32.jpg",
                            ItemID = 32
                        },
                        new
                        {
                            ImageID = 33,
                            ImagePath = "product33.jpg",
                            ItemID = 33
                        },
                        new
                        {
                            ImageID = 34,
                            ImagePath = "product34.jpg",
                            ItemID = 34
                        },
                        new
                        {
                            ImageID = 35,
                            ImagePath = "product35.jpg",
                            ItemID = 35
                        },
                        new
                        {
                            ImageID = 36,
                            ImagePath = "product36.jpg",
                            ItemID = 36
                        },
                        new
                        {
                            ImageID = 37,
                            ImagePath = "product37.jpg",
                            ItemID = 37
                        },
                        new
                        {
                            ImageID = 38,
                            ImagePath = "product38.jpg",
                            ItemID = 38
                        },
                        new
                        {
                            ImageID = 39,
                            ImagePath = "product39.jpg",
                            ItemID = 39
                        },
                        new
                        {
                            ImageID = 40,
                            ImagePath = "product40.jpg",
                            ItemID = 40
                        });
                });

            modelBuilder.Entity("INFT3050.Models.Item", b =>
                {
                    b.Property<int>("ItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemID"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int?>("Quantity")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("VitaminType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ItemID");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            ItemID = 1,
                            Category = "Heart Health",
                            Company = "Ocean Health",
                            DateAdded = new DateTime(2024, 7, 31, 17, 41, 59, 465, DateTimeKind.Local).AddTicks(2859),
                            Description = "Ocean Health Omega 3 Fish Oil 1000mg is a 100% natural dietary supplement that is a rich source of the Omega 3 essential fatty acids EPA and DHA derived from deep water fish.",
                            ItemName = "Omega-3 Fish Oil 1000mg 60s",
                            Price = 24.530000000000001,
                            Quantity = 10,
                            VitaminType = "Fish Oil"
                        },
                        new
                        {
                            ItemID = 2,
                            Category = "Eye Health",
                            Company = "Holistic Way",
                            DateAdded = new DateTime(2024, 7, 31, 17, 41, 59, 465, DateTimeKind.Local).AddTicks(2879),
                            Description = "Holistic Way Children's Eye Lutein Gummy may help to support healthy vision in children. Lutein is a potent antioxidant which helps to filter harmful blue light.",
                            ItemName = "Eye Lutein Gummy",
                            Price = 39.799999999999997,
                            Quantity = 2,
                            VitaminType = "Others"
                        },
                        new
                        {
                            ItemID = 3,
                            Category = "Immune System",
                            Company = "Holistic Way",
                            DateAdded = new DateTime(2024, 7, 31, 17, 41, 59, 465, DateTimeKind.Local).AddTicks(2881),
                            Description = "Holistic Way Vitamin C supports healthy immune system functioning, eases cold, flu and sore throat and stimulates collagen growth.",
                            ItemName = "Vitamin C 500mg 60s",
                            Price = 26.0,
                            Quantity = 15,
                            VitaminType = "Vitamin C"
                        },
                        new
                        {
                            ItemID = 4,
                            Category = "Overall Health",
                            Company = "Centrum",
                            DateAdded = new DateTime(2024, 7, 31, 17, 41, 59, 465, DateTimeKind.Local).AddTicks(2883),
                            Description = "Centrum Multivitamins provide essential vitamins and minerals to help support your overall health and well-being.",
                            ItemName = "Centrum Multivitamin",
                            Price = 50.0,
                            Quantity = 30,
                            VitaminType = "Multivitamins"
                        },
                        new
                        {
                            ItemID = 5,
                            Category = "Bone Health",
                            Company = "Nature Made",
                            DateAdded = new DateTime(2024, 7, 31, 17, 41, 59, 465, DateTimeKind.Local).AddTicks(2885),
                            Description = "Nature Made Calcium 600mg with Vitamin D3 helps support bone health and muscle function.",
                            ItemName = "Calcium 600mg + Vitamin D3",
                            Price = 22.0,
                            Quantity = 20,
                            VitaminType = "Calcium"
                        },
                        new
                        {
                            ItemID = 6,
                            Category = "Digestive Health",
                            Company = "Nature's Bounty",
                            DateAdded = new DateTime(2024, 7, 31, 17, 41, 59, 465, DateTimeKind.Local).AddTicks(2887),
                            Description = "Nature's Bounty Probiotic 10 contains 10 unique probiotic strains to support digestive health.",
                            ItemName = "Probiotic 10",
                            Price = 30.0,
                            Quantity = 15,
                            VitaminType = "Probiotics"
                        },
                        new
                        {
                            ItemID = 7,
                            Category = "Heart Health",
                            Company = "Nature's Bounty",
                            DateAdded = new DateTime(2024, 7, 31, 17, 41, 59, 465, DateTimeKind.Local).AddTicks(2889),
                            Description = "Nature's Bounty CoQ10 200mg supports heart health and energy production.",
                            ItemName = "CoQ10 200mg",
                            Price = 40.0,
                            Quantity = 10,
                            VitaminType = "CoQ10"
                        },
                        new
                        {
                            ItemID = 8,
                            Category = "Beauty",
                            Company = "Nature's Bounty",
                            DateAdded = new DateTime(2024, 7, 31, 17, 41, 59, 465, DateTimeKind.Local).AddTicks(2891),
                            Description = "Nature's Bounty Biotin supports healthy hair, skin, and nails.",
                            ItemName = "Biotin 5000mcg",
                            Price = 15.0,
                            Quantity = 25,
                            VitaminType = "Biotin"
                        },
                        new
                        {
                            ItemID = 9,
                            Category = "Bone Health",
                            Company = "Nature Made",
                            DateAdded = new DateTime(2024, 7, 31, 17, 41, 59, 465, DateTimeKind.Local).AddTicks(2892),
                            Description = "Nature Made Vitamin D3 1000 IU supports bone and immune health.",
                            ItemName = "Vitamin D3 1000 IU",
                            Price = 15.0,
                            Quantity = 20,
                            VitaminType = "Vitamin D"
                        },
                        new
                        {
                            ItemID = 10,
                            Category = "Heart Health",
                            Company = "Nordic Naturals",
                            DateAdded = new DateTime(2024, 7, 31, 17, 41, 59, 465, DateTimeKind.Local).AddTicks(2894),
                            Description = "Nordic Naturals Fish Oil 1200mg supports heart health and cognitive function.",
                            ItemName = "Fish Oil 1200mg",
                            Price = 25.0,
                            Quantity = 22,
                            VitaminType = "Fish Oil"
                        },
                        new
                        {
                            ItemID = 11,
                            Category = "Joint Health",
                            Company = "Nordic Naturals",
                            DateAdded = new DateTime(2024, 7, 31, 17, 41, 59, 465, DateTimeKind.Local).AddTicks(2896),
                            Description = "Nordic Naturals Curcumin 200mg supports joint health and inflammatory response.",
                            ItemName = "Curcumin 200mg",
                            Price = 35.0,
                            Quantity = 15,
                            VitaminType = "Curcumin"
                        },
                        new
                        {
                            ItemID = 12,
                            Category = "Digestive Health",
                            Company = "Nordic Naturals",
                            DateAdded = new DateTime(2024, 7, 31, 17, 41, 59, 465, DateTimeKind.Local).AddTicks(2898),
                            Description = "Nordic Naturals Probiotic Gummies support digestive health.",
                            ItemName = "Probiotic Gummies",
                            Price = 20.0,
                            Quantity = 25,
                            VitaminType = "Probiotics"
                        },
                        new
                        {
                            ItemID = 13,
                            Category = "Beauty",
                            Company = "Vital Proteins",
                            DateAdded = new DateTime(2024, 7, 31, 17, 41, 59, 465, DateTimeKind.Local).AddTicks(2900),
                            Description = "Vital Proteins Collagen Peptides support skin, hair, nail, and joint health.",
                            ItemName = "Collagen Peptides",
                            Price = 40.0,
                            Quantity = 20,
                            VitaminType = "Collagen"
                        },
                        new
                        {
                            ItemID = 14,
                            Category = "Immune System",
                            Company = "Vitafusion",
                            DateAdded = new DateTime(2024, 7, 31, 17, 41, 59, 465, DateTimeKind.Local).AddTicks(2901),
                            Description = "Vitafusion Vitamin C Gummies support immune system health.",
                            ItemName = "Vitamin C Gummies",
                            Price = 15.0,
                            Quantity = 30,
                            VitaminType = "Vitamin C"
                        },
                        new
                        {
                            ItemID = 15,
                            Category = "Overall Health",
                            Company = "Vitafusion",
                            DateAdded = new DateTime(2024, 7, 31, 17, 41, 59, 465, DateTimeKind.Local).AddTicks(2903),
                            Description = "Vitafusion Women's Multivitamin supports overall women's health.",
                            ItemName = "Women's Multivitamin",
                            Price = 25.0,
                            Quantity = 35,
                            VitaminType = "Multivitamins"
                        },
                        new
                        {
                            ItemID = 16,
                            Category = "Sleep Health",
                            Company = "Vitafusion",
                            DateAdded = new DateTime(2024, 7, 31, 17, 41, 59, 465, DateTimeKind.Local).AddTicks(2905),
                            Description = "Vitafusion Melatonin 5mg supports healthy sleep patterns.",
                            ItemName = "Melatonin 5mg",
                            Price = 10.0,
                            Quantity = 28,
                            VitaminType = "Melatonin"
                        },
                        new
                        {
                            ItemID = 17,
                            Category = "Energy",
                            Company = "Solgar",
                            DateAdded = new DateTime(2024, 7, 31, 17, 41, 59, 465, DateTimeKind.Local).AddTicks(2907),
                            Description = "Solgar Vitamin B Complex supports energy metabolism.",
                            ItemName = "Vitamin B Complex",
                            Price = 20.0,
                            Quantity = 20,
                            VitaminType = "Vitamin B"
                        },
                        new
                        {
                            ItemID = 18,
                            Category = "Overall Health",
                            Company = "Solgar",
                            DateAdded = new DateTime(2024, 7, 31, 17, 41, 59, 465, DateTimeKind.Local).AddTicks(2909),
                            Description = "Solgar Magnesium Citrate supports nerve and muscle function.",
                            ItemName = "Magnesium Citrate",
                            Price = 15.0,
                            Quantity = 18,
                            VitaminType = "Magnesium"
                        },
                        new
                        {
                            ItemID = 19,
                            Category = "Heart Health",
                            Company = "Solgar",
                            DateAdded = new DateTime(2024, 7, 31, 17, 41, 59, 465, DateTimeKind.Local).AddTicks(2911),
                            Description = "Solgar Folate 400mcg supports heart health and cellular function.",
                            ItemName = "Folate 400mcg",
                            Price = 12.0,
                            Quantity = 22,
                            VitaminType = "Folate"
                        },
                        new
                        {
                            ItemID = 20,
                            Category = "Immune System",
                            Company = "Solgar",
                            DateAdded = new DateTime(2024, 7, 31, 17, 41, 59, 465, DateTimeKind.Local).AddTicks(2913),
                            Description = "Solgar Vitamin E 200 IU supports immune and skin health.",
                            ItemName = "Vitamin E 200 IU",
                            Price = 18.0,
                            Quantity = 20,
                            VitaminType = "Vitamin E"
                        },
                        new
                        {
                            ItemID = 21,
                            Category = "Bone Health",
                            Company = "Solgar",
                            DateAdded = new DateTime(2024, 7, 31, 17, 41, 59, 465, DateTimeKind.Local).AddTicks(2915),
                            Description = "Solgar Vitamin K2 45mcg supports bone and heart health.",
                            ItemName = "Vitamin K2 45mcg",
                            Price = 20.0,
                            Quantity = 15,
                            VitaminType = "Vitamin K"
                        },
                        new
                        {
                            ItemID = 22,
                            Category = "Digestive Health",
                            Company = "Garden of Life",
                            DateAdded = new DateTime(2024, 7, 31, 17, 41, 59, 465, DateTimeKind.Local).AddTicks(2917),
                            Description = "Garden of Life Digestive Enzymes support healthy digestion.",
                            ItemName = "Digestive Enzymes",
                            Price = 22.0,
                            Quantity = 25,
                            VitaminType = "Digestive Enzymes"
                        },
                        new
                        {
                            ItemID = 23,
                            Category = "Beauty",
                            Company = "Garden of Life",
                            DateAdded = new DateTime(2024, 7, 31, 17, 41, 59, 465, DateTimeKind.Local).AddTicks(2919),
                            Description = "Garden of Life Collagen Peptides Powder supports healthy skin, hair, nails, and joints.",
                            ItemName = "Collagen Peptides Powder",
                            Price = 45.0,
                            Quantity = 20,
                            VitaminType = "Collagen"
                        },
                        new
                        {
                            ItemID = 24,
                            Category = "Overall Health",
                            Company = "Garden of Life",
                            DateAdded = new DateTime(2024, 7, 31, 17, 41, 59, 465, DateTimeKind.Local).AddTicks(2920),
                            Description = "Garden of Life Men's Multivitamin supports overall men's health.",
                            ItemName = "Men's Multivitamin",
                            Price = 30.0,
                            Quantity = 35,
                            VitaminType = "Multivitamins"
                        },
                        new
                        {
                            ItemID = 25,
                            Category = "Joint Health",
                            Company = "Garden of Life",
                            DateAdded = new DateTime(2024, 7, 31, 17, 41, 59, 465, DateTimeKind.Local).AddTicks(2922),
                            Description = "Garden of Life Turmeric 500mg supports joint health and inflammatory response.",
                            ItemName = "Turmeric 500mg",
                            Price = 28.0,
                            Quantity = 18,
                            VitaminType = "Turmeric"
                        },
                        new
                        {
                            ItemID = 26,
                            Category = "Immune System",
                            Company = "Garden of Life",
                            DateAdded = new DateTime(2024, 7, 31, 17, 41, 59, 465, DateTimeKind.Local).AddTicks(2924),
                            Description = "Garden of Life Vitamin C 1000mg supports immune system health.",
                            ItemName = "Vitamin C 1000mg",
                            Price = 20.0,
                            Quantity = 30,
                            VitaminType = "Vitamin C"
                        },
                        new
                        {
                            ItemID = 27,
                            Category = "Heart Health",
                            Company = "Spring Valley",
                            DateAdded = new DateTime(2024, 7, 31, 17, 41, 59, 465, DateTimeKind.Local).AddTicks(2926),
                            Description = "Spring Valley Fish Oil 1000mg supports heart and brain health.",
                            ItemName = "Fish Oil 1000mg",
                            Price = 28.0,
                            Quantity = 20,
                            VitaminType = "Fish Oil"
                        },
                        new
                        {
                            ItemID = 28,
                            Category = "Digestive Health",
                            Company = "Spring Valley",
                            DateAdded = new DateTime(2024, 7, 31, 17, 41, 59, 465, DateTimeKind.Local).AddTicks(2927),
                            Description = "Spring Valley Probiotic 50 Billion CFU supports digestive and immune health.",
                            ItemName = "Probiotic 50 Billion CFU",
                            Price = 40.0,
                            Quantity = 25,
                            VitaminType = "Probiotics"
                        },
                        new
                        {
                            ItemID = 29,
                            Category = "Immune System",
                            Company = "Nature's Way",
                            DateAdded = new DateTime(2024, 7, 31, 17, 41, 59, 465, DateTimeKind.Local).AddTicks(2931),
                            Description = "Nature's Way Elderberry Gummies support immune system health.",
                            ItemName = "Elderberry Gummies",
                            Price = 25.0,
                            Quantity = 30,
                            VitaminType = "Elderberry"
                        },
                        new
                        {
                            ItemID = 30,
                            Category = "Stress Relief",
                            Company = "Nature's Way",
                            DateAdded = new DateTime(2024, 7, 31, 17, 41, 59, 465, DateTimeKind.Local).AddTicks(2933),
                            Description = "Nature's Way Ashwagandha 500mg supports stress relief and energy.",
                            ItemName = "Ashwagandha 500mg",
                            Price = 20.0,
                            Quantity = 20,
                            VitaminType = "Herbal"
                        },
                        new
                        {
                            ItemID = 31,
                            Category = "Bone Health",
                            Company = "Nature's Way",
                            DateAdded = new DateTime(2024, 7, 31, 17, 41, 59, 465, DateTimeKind.Local).AddTicks(2935),
                            Description = "Nature's Way Vitamin D3 2000 IU supports bone and immune health.",
                            ItemName = "Vitamin D3 2000 IU",
                            Price = 18.0,
                            Quantity = 22,
                            VitaminType = "Vitamin D"
                        },
                        new
                        {
                            ItemID = 32,
                            Category = "Joint Health",
                            Company = "Nature's Way",
                            DateAdded = new DateTime(2024, 7, 31, 17, 41, 59, 465, DateTimeKind.Local).AddTicks(2972),
                            Description = "Nature's Way Turmeric Curcumin 1000mg supports joint health and inflammatory response.",
                            ItemName = "Turmeric Curcumin 1000mg",
                            Price = 30.0,
                            Quantity = 18,
                            VitaminType = "Turmeric"
                        },
                        new
                        {
                            ItemID = 33,
                            Category = "Brain Health",
                            Company = "Nature's Way",
                            DateAdded = new DateTime(2024, 7, 31, 17, 41, 59, 465, DateTimeKind.Local).AddTicks(2973),
                            Description = "Nature's Way Ginkgo Biloba 120mg supports brain function and mental alertness.",
                            ItemName = "Ginkgo Biloba 120mg",
                            Price = 22.0,
                            Quantity = 15,
                            VitaminType = "Herbal"
                        },
                        new
                        {
                            ItemID = 34,
                            Category = "Digestive Health",
                            Company = "Lake Avenue",
                            DateAdded = new DateTime(2024, 7, 31, 17, 41, 59, 465, DateTimeKind.Local).AddTicks(2975),
                            Description = "Lake Avenue Probiotic 25 Billion CFU supports digestive health and immune function.",
                            ItemName = "Probiotic 25 Billion CFU",
                            Price = 35.0,
                            Quantity = 25,
                            VitaminType = "Probiotics"
                        },
                        new
                        {
                            ItemID = 35,
                            Category = "Immune System",
                            Company = "Nature's Bounty",
                            DateAdded = new DateTime(2024, 7, 31, 17, 41, 59, 465, DateTimeKind.Local).AddTicks(2977),
                            Description = "Nature's Bounty Vitamin C with Rose Hips 1000mg supports immune system health.",
                            ItemName = "Vitamin C with Rose Hips 1000mg",
                            Price = 15.0,
                            Quantity = 30,
                            VitaminType = "Vitamin C"
                        },
                        new
                        {
                            ItemID = 36,
                            Category = "Immune System",
                            Company = "Nature's Bounty",
                            DateAdded = new DateTime(2024, 7, 31, 17, 41, 59, 465, DateTimeKind.Local).AddTicks(2979),
                            Description = "Nature's Bounty Zinc 50mg supports immune system health.",
                            ItemName = "Zinc 50mg",
                            Price = 12.0,
                            Quantity = 20,
                            VitaminType = "Zinc"
                        },
                        new
                        {
                            ItemID = 37,
                            Category = "Energy",
                            Company = "Nature's Bounty",
                            DateAdded = new DateTime(2024, 7, 31, 17, 41, 59, 465, DateTimeKind.Local).AddTicks(2981),
                            Description = "Nature's Bounty Vitamin B12 1000mcg supports energy metabolism and nervous system health.",
                            ItemName = "Vitamin B12 1000mcg",
                            Price = 18.0,
                            Quantity = 22,
                            VitaminType = "Vitamin B"
                        },
                        new
                        {
                            ItemID = 38,
                            Category = "Overall Health",
                            Company = "Nature's Bounty",
                            DateAdded = new DateTime(2024, 7, 31, 17, 41, 59, 465, DateTimeKind.Local).AddTicks(2983),
                            Description = "Nature's Bounty Iron 65mg supports red blood cell production and energy metabolism.",
                            ItemName = "Iron 65mg",
                            Price = 10.0,
                            Quantity = 20,
                            VitaminType = "Iron"
                        },
                        new
                        {
                            ItemID = 39,
                            Category = "Bone Health",
                            Company = "Citracal",
                            DateAdded = new DateTime(2024, 7, 31, 17, 41, 59, 465, DateTimeKind.Local).AddTicks(2985),
                            Description = "Citracal Calcium Citrate 600mg supports bone health and muscle function.",
                            ItemName = "Calcium Citrate 600mg",
                            Price = 25.0,
                            Quantity = 20,
                            VitaminType = "Calcium"
                        },
                        new
                        {
                            ItemID = 40,
                            Category = "Immune System",
                            Company = "Sambucol",
                            DateAdded = new DateTime(2024, 7, 31, 17, 41, 59, 465, DateTimeKind.Local).AddTicks(2987),
                            Description = "Sambucol Elderberry Syrup supports immune system health with high antioxidant levels.",
                            ItemName = "Elderberry Syrup",
                            Price = 20.0,
                            Quantity = 15,
                            VitaminType = "Elderberry"
                        });
                });

            modelBuilder.Entity("INFT3050.Models.Order", b =>
                {
                    b.Property<int>("OrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderID"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<double>("OrderHistorySubtotal")
                        .HasColumnType("float");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("UserID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("OrderID");

                    b.HasIndex("UserID");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("INFT3050.Models.OrderItem", b =>
                {
                    b.Property<int>("OrderItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderItemID"));

                    b.Property<int>("ItemID")
                        .HasColumnType("int");

                    b.Property<int>("OrderID")
                        .HasColumnType("int");

                    b.Property<double>("OrderItemStubtotal")
                        .HasColumnType("float");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("OrderItemID");

                    b.HasIndex("ItemID");

                    b.HasIndex("OrderID");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("INFT3050.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("INFT3050.Models.Image", b =>
                {
                    b.HasOne("INFT3050.Models.Item", "Item")
                        .WithMany("Images")
                        .HasForeignKey("ItemID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("INFT3050.Models.Order", b =>
                {
                    b.HasOne("INFT3050.Models.User", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("INFT3050.Models.OrderItem", b =>
                {
                    b.HasOne("INFT3050.Models.Item", "item")
                        .WithMany("OrderItems")
                        .HasForeignKey("ItemID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("INFT3050.Models.Order", "order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("item");

                    b.Navigation("order");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("INFT3050.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("INFT3050.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("INFT3050.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("INFT3050.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("INFT3050.Models.Item", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("INFT3050.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("INFT3050.Models.User", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
